#!/usr/bin/env python3
"""D0-R: build provenance manifest for functional-anchor artifacts.

Records SHA-256, size, schema_version, and regeneration commands for every
D0-R functional-anchor artifact and raw RDAT input. All artifacts under
artifacts/ remain gitignored (tracked_in_git=false); only this manifest and
reports/d0r_data_feasibility_audit.md are tracked. This preserves the
'artifacts/ never tracked' boundary while keeping full provenance (hashes +
regen commands) in version control.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

SCHEMA = "reactflow-delta-d0r-functional-anchor-provenance-manifest-v1"

REPO = Path("/home/cunyuliu/reactflow_delta_goal_20260729")
ART = REPO / "artifacts/reactflow_delta/d0r"
M2SL5_DIR = Path("/mnt/cunyuliu/reactflow_delta_raw/rmdb/fixtures_20260730T125000+0800")
PAPER_DIR = Path("/mnt/cunyuliu/reactflow_delta_raw/rmdb/paper_accession_38427602_20260730T143800+0800")

CMD_AUDIT = (
    "PYTHONPATH=src python scripts/reactflow_delta/d0r_functional_anchor_audit.py "
    f"--m2sl5-dir {M2SL5_DIR} --paper-dir {PAPER_DIR} --output-dir artifacts/reactflow_delta/d0r"
)
CMD_ACCEPT = (
    "PYTHONPATH=src python scripts/reactflow_delta/d0r_build_functional_acceptance.py "
    "--summary artifacts/reactflow_delta/d0r/d0r_functional_anchor_summary.json "
    "--m2sl5-relations artifacts/reactflow_delta/d0r/m2sl5_functional_candidate_relations.json "
    "--covsl5-relations artifacts/reactflow_delta/d0r/covsl5_sl5cv2_candidate_relations.json "
    "--output-dir artifacts/reactflow_delta/d0r --python <env-python> "
    "--test-dir tests/reactflow_delta --input-rdat <10 RDAT files>"
)


def sha256_size(path: Path) -> dict:
    if not path.is_file():
        return {"path": str(path), "exists": False, "sha256": None, "size_bytes": 0}
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return {"path": str(path), "exists": True, "sha256": digest.hexdigest(),
            "size_bytes": path.stat().st_size}


def read_schema(path: Path) -> str | None:
    try:
        with path.open() as f:
            return json.load(f).get("schema_version")
    except Exception:
        return None


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--documented-code-commit",
        required=True,
        help="The functional-anchor code commit this manifest documents (e.g. ed4c565).",
    )
    parser.add_argument(
        "--acceptance-python",
        default=sys.executable,
        help="Interpreter used to regenerate the acceptance (for version recording).",
    )
    args = parser.parse_args()

    artifacts: list[dict] = []

    new_arts = [
        ("d0r_functional_anchor_audit.json", CMD_AUDIT, True),
        ("m2sl5_functional_candidate_relations.json", CMD_AUDIT, True),
        ("covsl5_sl5cv2_candidate_relations.json", CMD_AUDIT, True),
        ("d0r_functional_anchor_summary.json", CMD_AUDIT, True),
        ("d0r_acceptance_v2.json", CMD_ACCEPT, True),
        ("d0r_data_feasibility_audit.md", CMD_ACCEPT, True),
    ]
    for name, cmd, regenerable in new_arts:
        p = ART / name
        info = sha256_size(p)
        info["relative_path"] = f"artifacts/reactflow_delta/d0r/{name}"
        info["schema_version"] = read_schema(p) if name.endswith(".json") else None
        info["tracked_in_git"] = False
        info["regenerable"] = regenerable
        info["regeneration_command"] = cmd
        artifacts.append(info)

    preexisting = [
        ("d0r_construct_audit.json",
         "preexisting D0-R construct audit (SEQPOS-based); not regenerated by functional-anchor task"),
        ("d0r_acceptance.json",
         "preexisting D0-R acceptance v1 (SEQPOS-based); superseded by d0r_acceptance_v2.json, preserved per handoff"),
        ("m2sl5_candidate_relations.json",
         "preexisting SEQPOS-based candidate relations; preserved as historical evidence, not overwritten"),
    ]
    for name, note in preexisting:
        p = ART / name
        info = sha256_size(p)
        info["relative_path"] = f"artifacts/reactflow_delta/d0r/{name}"
        info["schema_version"] = read_schema(p) if name.endswith(".json") else None
        info["tracked_in_git"] = False
        info["regenerable"] = False
        info["note"] = note
        artifacts.append(info)

    raw_inputs: list[dict] = []
    raw_files = sorted(M2SL5_DIR.glob("M2SL5_*.rdat")) + sorted(PAPER_DIR.glob("*.rdat"))
    for p in raw_files:
        info = sha256_size(p)
        info["relative_path"] = None
        info["tracked_in_git"] = False
        info["regeneration_command"] = (
            "python scripts/reactflow_delta/d0r_download_assets.py "
            "(RMDB download with sha256 verification)"
        )
        raw_inputs.append(info)

    report_src = ART / "d0r_data_feasibility_audit.md"
    report_dst = REPO / "reports/d0r_data_feasibility_audit.md"
    report_info = sha256_size(report_dst)
    report_info["relative_path"] = "reports/d0r_data_feasibility_audit.md"
    report_info["tracked_in_git"] = True
    report_info["source_artifact"] = "artifacts/reactflow_delta/d0r/d0r_data_feasibility_audit.md"
    report_info["source_sha256"] = sha256_size(report_src)["sha256"]
    report_info["regeneration_command"] = CMD_ACCEPT

    try:
        commit = subprocess.check_output(
            ["git", "-C", str(REPO), "rev-parse", "HEAD"], text=True
        ).strip()
    except Exception:
        commit = None

    # Resolve the documented code commit (the functional-anchor implementation)
    # to its full hash. This binds provenance to that specific code commit,
    # independent of when the manifest is regenerated.
    documented_commit = args.documented_code_commit
    try:
        documented_commit = subprocess.check_output(
            ["git", "-C", str(REPO), "rev-parse", args.documented_code_commit],
            text=True,
        ).strip()
    except Exception:
        pass  # keep the short/arg value if resolution fails

    try:
        acc_python_version = subprocess.check_output(
            [args.acceptance_python, "--version"], text=True
        ).strip()
    except Exception:
        acc_python_version = None

    manifest = {
        "schema_version": SCHEMA,
        "stage": "D0-R",
        "generated_at": datetime.now(timezone.utc).astimezone().isoformat(),
        "git_commit_at_generation": commit,
        "documented_code_commit": documented_commit,
        "acceptance_python_interpreter": args.acceptance_python,
        "acceptance_python_version": acc_python_version,
        "audit_method": "functional_anchor_124nt_window_offset_31",
        "code_version": {
            "module": "src/reactflow/delta/d0r_functional.py",
            "audit_script": "scripts/reactflow_delta/d0r_functional_anchor_audit.py",
            "acceptance_script": "scripts/reactflow_delta/d0r_build_functional_acceptance.py",
            "manifest_script": "scripts/reactflow_delta/d0r_build_provenance_manifest.py",
            "tests": "tests/reactflow_delta/test_d0r_functional_anchor.py",
        },
        "boundary_note": (
            "All artifacts under artifacts/ are gitignored (tracked_in_git=false). "
            "Only this manifest and reports/d0r_data_feasibility_audit.md are tracked. "
            "Large per-profile JSON (d0r_functional_anchor_audit.json, "
            "d0r_construct_audit.json) is regenerable intermediate data and is NOT "
            "stored in git history; provenance is captured here via sha256 + size + "
            "regeneration commands. documented_code_commit binds this manifest to the "
            "functional-anchor implementation commit; acceptance_python_version records "
            "the interpreter required for acceptance regeneration (Python 3.11 per "
            "project contract)."
        ),
        "raw_inputs": raw_inputs,
        "artifacts": artifacts,
        "tracked_report": report_info,
        "scientific_boundary": (
            "Provenance manifest only. No pair, tier, or model claim. Candidate "
            "relations are unverified (candidate_only_pending_parent_lineage_and_"
            "functional_region_validation, true_pair=false)."
        ),
    }
    out = REPO / "manifests/reactflow_delta/d0r/d0r_functional_anchor_manifest.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(manifest, indent=2, ensure_ascii=False, sort_keys=True))
    print(f"Wrote: {out}")
    print(json.dumps({
        "artifacts_count": len(artifacts),
        "raw_inputs_count": len(raw_inputs),
        "largest_artifact_bytes": max(a["size_bytes"] for a in artifacts),
        "largest_artifact": max(artifacts, key=lambda a: a["size_bytes"])["relative_path"],
    }, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
