"""ReactFlow public API.

ReactFlow is implemented as a small, testable scientific-computing core before
any large model training code is introduced.  The public modules expose the
mathematical objects needed by the research plan:

* dataset source manifests and reactivity preprocessing;
* RNA 2D legality constraints and projection;
* differentiable reactivity forward operators;
* physics-inspired thermodynamic priors and guidance;
* discrete flow matching primitives and the pairwise denoiser;
* the end-to-end ``L_DFM + lambda_r L_react`` training pilot;
* symbolic checks for the loss derivations;
* lightweight SVG visual diagnostics.
"""

from reactflow.constraints import (
    PairValidationResult,
    pairs_to_matrix,
    project_greedy_matching,
    project_max_weight_nested,
    validate_pair_matrix,
)
from reactflow.checkpoint import (
    CHECKPOINT_SCHEMA_VERSION,
    TrainingCheckpoint,
    read_training_checkpoint,
    write_training_checkpoint,
)
from reactflow.contact import (
    contact_denoising_bce,
    contact_denoising_logit_gradient,
    soft_contact_matrix,
)
from reactflow.data import (
    EfoldRecord,
    RibonanzaProfile,
    efold_pair_matrix,
    normalize_profile,
    parse_efold_record,
    read_efold_json,
    validate_profile,
)
from reactflow.dfm import (
    conditional_rate_matrix,
    denoising_cross_entropy,
    mixture_path_marginal,
    softmax_cross_entropy_gradient,
    uniform_source,
)
from reactflow.evaluate import (
    CalibrationBin,
    CalibrationReport,
    ComparisonRow,
    ComparisonTable,
    GeneralizationGap,
    ReactivityMetrics,
    StructurePrediction,
    TierMetrics,
    build_comparison_table,
    calibrated_mae,
    expected_calibration_error,
    generalization_gap,
    reactivity_metrics,
    render_comparison_markdown,
    spearman_correlation,
    structure_distance_bin_metrics_by_tier,
    structure_metrics_by_tier,
)
from reactflow.features import (
    AdapterGradients,
    AdapterParameters,
    FeatureAdapter,
    FrozenFeatureLookup,
    adapter_sgd_update,
    build_augmented_features,
    load_frozen_features,
    split_feature_gradient,
    zero_single_rows,
)
from reactflow.frozen import (
    FrozenFeatureProvenance,
    FrozenFeatureRecord,
    FrozenShard,
    default_schema,
    read_frozen_shard,
    write_frozen_shard,
)
from reactflow.inference import (
    DecoderConfig,
    InferenceConfig,
    InferenceMode,
    InferenceResult,
    MatchingPolicy,
    decode_calibrated_marginal,
    pair_vs_unpaired_log_odds,
    predict_structure,
)
from reactflow.model import DenoiserParameters, PairwiseDenoiser, marginal_pair_matrix
from reactflow.npio import NdArray, load_npy, load_npz, save_npy, save_npz
from reactflow.probing import (
    ProbeCalibration,
    ProfilePrediction,
    aggregate_full_profiles,
    calibration_manifest,
    fit_probe_calibration,
)
from reactflow.reactivity import ReactivityForwardOperator, ReactivityParameters, reactivity_consistency_loss
from reactflow.sampling import (
    SampledStructure,
    ensemble_unpaired_probability,
    pairing_frequency_matrix,
    sample_structure,
    sample_structures,
)
from reactflow.splits import (
    SplitAssignment,
    SplitCacheSummary,
    SplitManifest,
    SplitRecord,
    build_split_manifest,
    length_bucket_label,
    manifest_from_json,
    manifest_to_json,
    read_split_metadata_tsv,
    split_efold_cache_by_clan,
    validate_split_leakage,
)
from reactflow.synthetic import SyntheticSample, make_dataset
from reactflow.thermo import (
    GuidanceScanPoint,
    energy_guided_scores,
    guidance_eta_scan,
    guidance_scan_is_monotone,
    structure_energy,
    structure_pair_energy,
)
from reactflow.train import TrainConfig, TrainingResult, train_pilot
from reactflow.train import (
    EfoldCacheSummary,
    bucket_samples_by_length,
    build_efold_sample_cache,
    iter_efold_record_windows,
    load_efold_samples,
    order_samples_by_length_bucket,
    order_samples_family_balanced,
    order_samples_for_training,
    read_sample_cache,
    sample_from_cache_obj,
    sample_from_efold_record,
    sample_to_cache_obj,
    train_pilot_torch,
    window_efold_record,
)
from reactflow.visualization import write_guidance_scan_svg

__all__ = [
    "AdapterGradients",
    "AdapterParameters",
    "CHECKPOINT_SCHEMA_VERSION",
    "CalibrationBin",
    "CalibrationReport",
    "ComparisonRow",
    "ComparisonTable",
    "DenoiserParameters",
    "DecoderConfig",
    "EfoldCacheSummary",
    "EfoldRecord",
    "FeatureAdapter",
    "FrozenFeatureLookup",
    "FrozenFeatureProvenance",
    "FrozenFeatureRecord",
    "FrozenShard",
    "GeneralizationGap",
    "GuidanceScanPoint",
    "InferenceConfig",
    "InferenceMode",
    "InferenceResult",
    "NdArray",
    "MatchingPolicy",
    "PairValidationResult",
    "PairwiseDenoiser",
    "ProbeCalibration",
    "ProfilePrediction",
    "ReactivityForwardOperator",
    "ReactivityMetrics",
    "ReactivityParameters",
    "RibonanzaProfile",
    "SampledStructure",
    "SplitAssignment",
    "SplitCacheSummary",
    "SplitManifest",
    "SplitRecord",
    "StructurePrediction",
    "SyntheticSample",
    "TierMetrics",
    "TrainConfig",
    "TrainingCheckpoint",
    "TrainingResult",
    "adapter_sgd_update",
    "aggregate_full_profiles",
    "build_augmented_features",
    "build_comparison_table",
    "build_efold_sample_cache",
    "build_split_manifest",
    "bucket_samples_by_length",
    "calibrated_mae",
    "calibration_manifest",
    "conditional_rate_matrix",
    "contact_denoising_bce",
    "contact_denoising_logit_gradient",
    "default_schema",
    "denoising_cross_entropy",
    "decode_calibrated_marginal",
    "efold_pair_matrix",
    "energy_guided_scores",
    "ensemble_unpaired_probability",
    "expected_calibration_error",
    "fit_probe_calibration",
    "generalization_gap",
    "guidance_eta_scan",
    "guidance_scan_is_monotone",
    "iter_efold_record_windows",
    "length_bucket_label",
    "load_efold_samples",
    "load_frozen_features",
    "load_npy",
    "load_npz",
    "make_dataset",
    "manifest_from_json",
    "manifest_to_json",
    "marginal_pair_matrix",
    "mixture_path_marginal",
    "normalize_profile",
    "order_samples_by_length_bucket",
    "order_samples_family_balanced",
    "order_samples_for_training",
    "pairing_frequency_matrix",
    "pair_vs_unpaired_log_odds",
    "pairs_to_matrix",
    "parse_efold_record",
    "project_greedy_matching",
    "project_max_weight_nested",
    "predict_structure",
    "read_efold_json",
    "read_frozen_shard",
    "read_sample_cache",
    "read_split_metadata_tsv",
    "read_training_checkpoint",
    "reactivity_consistency_loss",
    "reactivity_metrics",
    "render_comparison_markdown",
    "sample_structure",
    "sample_from_cache_obj",
    "sample_from_efold_record",
    "sample_structures",
    "sample_to_cache_obj",
    "save_npy",
    "save_npz",
    "soft_contact_matrix",
    "softmax_cross_entropy_gradient",
    "spearman_correlation",
    "split_efold_cache_by_clan",
    "split_feature_gradient",
    "structure_energy",
    "structure_distance_bin_metrics_by_tier",
    "structure_metrics_by_tier",
    "structure_pair_energy",
    "train_pilot",
    "train_pilot_torch",
    "uniform_source",
    "validate_pair_matrix",
    "validate_profile",
    "validate_split_leakage",
    "window_efold_record",
    "write_frozen_shard",
    "write_guidance_scan_svg",
    "write_training_checkpoint",
    "zero_single_rows",
]
